name: proyecto1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  html: ^0.15.6
  http: ^1.4.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  photo_view: ^0.15.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
